import type { Metadata } from "next";
import { Bebas_Neue, Lato } from "next/font/google";
import "./globals.scss";
import Footer from "./components/surfaces/footer/Footer";
import Navbar from "./components/surfaces/navbar/Navbar";

const bebasNeue = Bebas_Neue({
	subsets: ["latin"],
	weight: "400",
	variable: "--font-bebas-neue",
});

const lato = Lato({
	subsets: ["latin"],
	weight: ["300", "400", "700"],
	variable: "--font-lato",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${bebasNeue.variable} ${lato.variable}`}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
